import { Mulish } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/Footer";

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
  fallback: ["Arial", "Helvetica", "sans-serif"],
})

export const metadata = {
  title: "PT Milenium Jaya Sejati",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={mulish.className}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
